insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'AAmal Al-Showra', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (123, 'ABC Company', 'English-American', 'Y', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'AL Bazai', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'AL-QASSIM CARS EXHIB', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (3, 'Abdullah Hashim Co. Ltd.', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Abdullatif Alissa Auto. Co.', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Abdulmohsen Abdullah Alabdaly', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Advanced Lane car showroom', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Afdalih Al-Kaleej', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al - Rasheed Motors Co. Ltd .', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al Ghazi Exhb. For Car', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al Jazeerah', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al Jonoub', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al Mamlakah Gate', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al motaoakl', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al sayat', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al-Aqeel', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al-Falah', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al-Gsan', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al-Motaheda', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al-Wkalah Al-Arabia', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Al-Yemni motors – Issuzu', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'AlESAY', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Alhamrani Trading & Import Co.', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Alhamrani United Co .', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Alinjaz', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (4, 'Aljazirah Vehicles Agencies Co', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Aljomaih Automotive Comp Jedah', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Aljomaih Automotive Comp Riyad', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Almajdouie Motors', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Almulhim AUTO service company', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Althougan Automotive', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Aotu Star', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'BARAYAN', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Bahjat Assir', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Balbaid AutoZone', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Balubaid', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Dar Al Yazeedcar', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Dhil AlJazeerah Cars', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Doghmal Trading Co. Limited', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Eid Awaad Al Shwameancar', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'First Advanced Auto', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'First Motor Co AlFuttaim Group', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Foud Abdullah Barashi', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Habob Najed', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Haji Husein Alireza & Co.Ltd', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Hamad Al-Jomaih', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Harley - Davidson', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Harley - Davidson of Dhahran', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Hasan Al-Bashrawi', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Hussain Ahmed Alzbede', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Inter Road Co for Trad & Maint', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Issuzu', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Khalaf FarhanKhallafAlanazicar', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Khamees Mushait', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Kia Motors Saudi Arabia', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Modern excellencecar showroom', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Mohamed Yousuf Naghi Motors', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (5, 'Mohammad Al-Mutlaq Harley Davi', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Mohammed Abdullah Al-Thomali', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Mohammed Basheer Al Balwi', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Mohammed Fahaid Aladeem', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Mohsen Moshre Al Motairi', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Naifat Al-Qaseem CARS', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Najed', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'RB Auto Leasing Centers', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Saeed Ali Alaklaby', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Saeed Salem Al-Shahrani Exhib', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Safari', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Samaco', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Sayah Hadhary Aldabesi', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Sharaf Al-Thobaiti', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Shomk Al Yazancar', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Tajart Al khear', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Universal Motors Agencies', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Wallan Automotive', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'Wesam Aseer Showrrom for Cars', 'English-American', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (5, 'أبناء محمد علي المطلق', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'أعمال الشورى', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'افضلية الخليج للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'البازعي  للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'التوكيلات العالمية للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الجميح للسيارات الرياض', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الجميح للسيارات جدة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الحاج حسين علي رضا وشركاه المح', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الحمراني المتحدة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الحمراني للتجارة والاستيراد', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الذوقان للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الرشيد للسيارات المحدودة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'السياط للسيارات (هوندا)', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الشركةالاولى المتقدمة للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'العيسائي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الغسان', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الكيا السعودية للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'المتحدة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'المتوكل للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'المجدوعي للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الملحم لخدمات السيارات القابضة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الوعلان للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'الوكالة العربيه', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'اليمني للسيارات – أيسوزو', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'اوتو ستار', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'ايسوزو', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'بالبيد للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'بنك الرياض', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'بهجة عسير', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'تجارة الخير للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (4, 'توكيلات الجزيرة للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'حمد مسعود آل جميح', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'سفاري للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'سماكو', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'شركة الأولى للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'شركة الفلاح للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'شركة بالبيد للسيارات - أوتوزون', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'شركة دغمل للتجارة المحدودة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'شركةالطريق الدولي للتجارةوالصي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'صالةسعيدعلي الأكلبي لبيع وشراء', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'صاله وسام عسير للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'عبداللطيف العيسى للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (3, 'عبدالله هاشم المحدودة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'فرع الجزيره لبيع وشراءالسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'فرع مؤسسة الامتياز الحديث', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'فرع مؤسسة بوابة المملكة', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'فرع مؤسسة عيد عواد الشوامين', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'فرع مؤسسة محمد بشير البلوي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة المسار المطور للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة باريان', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة حسين أحمد الزبيدي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة خلف فرحان خلاف العنزي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة دار اليزيد للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة شموخ اليزن للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة صياح حضري الدبيسي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة محسن مشرع المطيري للسيار', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة موسى حسن البشراوي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسة نايفات القصيم', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسةشرف مقبول عبدالله الثبيتي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسةعبدالمحسن عبدالله العبدلي', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'مؤسسةمحمدعبدالله الثمالي التجا', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'محمد يوسف ناغي للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض الإنجاز للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض الجنوب للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض العقيل للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض الغازي للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض القصيم للسيارت', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض خميس مشيط للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض سعيد سالم الشهراني', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض ظل الجزيره للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض فؤادعبدالله براشي للسيارا', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض محمد فهيد العديم للسيارات', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'معرض نجد', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'هارلي ديفدسون', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
insert into dealerdb.dealer (dealer_code, dealer_name, language, preferred_dealer, sales_partner, used_category) values (12, 'هبوب نجد', 'Arabic (Saudi Arabia)', 'N', 'N', 0);
commit;
